// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0KuJPSECvbwvMCol_2uPzKzpsxl4YlEA',
    appId: '1:66664375213:web:cd48bec7a456a4c0c17724',
    messagingSenderId: '66664375213',
    projectId: 'restaurant-ca31d',
    authDomain: 'restaurant-ca31d.firebaseapp.com',
    storageBucket: 'restaurant-ca31d.appspot.com',
    measurementId: 'G-FFMVY3ZHBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2WHhL4wTGcIetKKRnlEC06VL4863Cg18',
    appId: '1:66664375213:android:14cfae29aae98d98c17724',
    messagingSenderId: '66664375213',
    projectId: 'restaurant-ca31d',
    storageBucket: 'restaurant-ca31d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC_WgkCyzG8vtCd8arV5vjo_C9mhtbkf8',
    appId: '1:66664375213:ios:eb0b5b5e292e3a6cc17724',
    messagingSenderId: '66664375213',
    projectId: 'restaurant-ca31d',
    storageBucket: 'restaurant-ca31d.appspot.com',
    iosBundleId: 'com.example.restaurent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC_WgkCyzG8vtCd8arV5vjo_C9mhtbkf8',
    appId: '1:66664375213:ios:f992f8b79d15aa36c17724',
    messagingSenderId: '66664375213',
    projectId: 'restaurant-ca31d',
    storageBucket: 'restaurant-ca31d.appspot.com',
    iosBundleId: 'com.example.restaurent.RunnerTests',
  );
}
